from .BaseWidget import BaseWidget
from .CustomDialog import CustomDialog
from .EmployeeWidget import EmployeeWidget
from .FormAddProduct import FormAddProduct
from .LoginWidget import LoginWidget
from .ManagementWidget import ManagementWidget
from .ModifyEmployeeWidget import ModifyEmployeeWidget
from .ModifyProductWidget import ModifyProductWidget
from .View import View
