from .base_widget import BaseWidget
from .custom_dialog import CustomDialog
from .employee_widget import EmployeeWidget
from .form_add_product import FormAddProduct
from .login_widget import LoginWidget
from .management_widget import ManagementWidget
from .modify_employee_widget import ModifyEmployeeWidget
from .modify_product_widget import ModifyProductWidget
from .view import View
